route:
    receiver: 'slack'

receivers:
    # Configure receivers here 
    # See: https://prometheus.io/docs/alerting/latest/configuration/

    # - name: 'slack'
    #   slack_configs:
    #       - send_resolved: true
    #         text: "{{ .CommonAnnotations.description }}"
    #         username: 'Prometheus'
    #         channel: '#prometheus'
    #         api_url: 'https://hooks.slack.com/services/xxxxxxxxx/uuuuuuuuu/zzzzzzzzzzzzzzzzzzzz'
