global:
  scrape_interval:     6s
  evaluation_interval: 6s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 6s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8001']

  - job_name: 'osmosis'
    scrape_interval: 6s
    static_configs:
      - targets: ["osmosis:26662"]

  - job_name: 'prometheus'
    scrape_interval: 6s
    static_configs:
      - targets: ['prometheus:9090']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'
